#include <gtest/gtest.h>

extern "C" {
#include <rtsyn/spsc/defaults.h>
}

TEST(SPSCDefaultsTest, ExposesSharedMemoryNames)
{
    EXPECT_STREQ(RTSYN_SPSC_DEFAULT_COMMAND_QUEUE, "/rtsyn_commands");
    EXPECT_STREQ(RTSYN_SPSC_DEFAULT_TELEMETRY_QUEUE, "/rtsyn_telemetry");
    EXPECT_STREQ(RTSYN_SPSC_DEFAULT_TELEMETRY_VALUES_QUEUE, "/rtsyn_telemetry_values");
    EXPECT_EQ(RTSYN_SPSC_SHM_NAME_MAX, 256);
    EXPECT_EQ(RTSYN_SPSC_FALLBACK_PAGE_SIZE, 4096);
}

TEST(SPSCDefaultsTest, ExposesEnvironmentNames)
{
    EXPECT_STREQ(RTSYN_SPSC_ENV_COMMAND_QUEUE, "RTSYN_COMMAND_QUEUE");
    EXPECT_STREQ(RTSYN_SPSC_ENV_TELEMETRY_QUEUE, "RTSYN_TELEMETRY_QUEUE");
    EXPECT_STREQ(RTSYN_SPSC_ENV_TELEMETRY_VALUES_QUEUE, "RTSYN_TELEMETRY_VALUES");
}
