#include <gtest/gtest.h>

extern "C" {
#include <rtsyn/api/defaults.h>
}

TEST(ApiDefaultsTest, ExposesHttpDefaults)
{
    EXPECT_STREQ(RTSYN_API_DEFAULT_HOST, "0.0.0.0");
    EXPECT_EQ(RTSYN_API_DEFAULT_PORT, 17190);
    EXPECT_STREQ(RTSYN_API_DEFAULT_VALUES_FILE, "/tmp/rtsyn-values");
    EXPECT_EQ(RTSYN_API_DEFAULT_MAX_TELEMETRY_EVENTS_PER_DRAIN, 256);
    EXPECT_EQ(RTSYN_API_DEFAULT_RECENT_TELEMETRY_EVENTS, 256);
    EXPECT_EQ(RTSYN_API_DEFAULT_TELEMETRY_DRAIN_PERIOD_MS, 5);
    EXPECT_STREQ(RTSYN_API_ENDPOINT_HEALTH, "/health");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_CAPABILITIES, "/capabilities");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_TELEMETRY_EVENTS, "/telemetry/events");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_TELEMETRY_VALUES_FILE, "/telemetry/values-file");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_TELEMETRY_CSV_FILE, "/telemetry/csv-file");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_MEASUREMENTS, "/measurements");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_GLOBAL, "/commands/global");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_LOAD_PLUGIN, "/commands/plugin/load");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_ADD_PLUGIN, "/commands/plugin/add");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_LOAD_DEVICE, "/commands/device/load");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_ADD_DEVICE, "/commands/device/add");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_SET_PARAM, "/commands/param");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_RUNTIME_PERIOD, "/commands/runtime/period");
    EXPECT_STREQ(RTSYN_API_ENDPOINT_COMMAND_RUNTIME_PRIORITY, "/commands/runtime/priority");
}

TEST(ApiDefaultsTest, ExposesHttpStatusDefaults)
{
    EXPECT_EQ(RTSYN_API_HTTP_STATUS_ACCEPTED, 202);
    EXPECT_EQ(RTSYN_API_HTTP_STATUS_BAD_REQUEST, 400);
    EXPECT_EQ(RTSYN_API_HTTP_STATUS_UNAVAILABLE, 503);
}

TEST(ApiDefaultsTest, ExposesEnvironmentNames)
{
    EXPECT_STREQ(RTSYN_API_ENV_HOST, "RTSYN_API_HOST");
    EXPECT_STREQ(RTSYN_API_ENV_PORT, "RTSYN_API_PORT");
    EXPECT_STREQ(RTSYN_API_ENV_CREATE_QUEUES, "RTSYN_API_CREATE_QUEUES");
    EXPECT_STREQ(RTSYN_API_ENV_VALUES_FILE, "RTSYN_VALUES_FILE");
}
