#include <gtest/gtest.h>

extern "C" {
#include <rtsyn/engine/defaults.h>
}

TEST(EngineDefaultsTest, ExposesEngineDefaults)
{
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_COMMAND_BUDGET, 64u);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_RT_THREAD_POLICY, SCHED_FIFO);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_RT_THREAD_PRIORITY, 99);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_RT_THREAD_INHERITSCHED, PTHREAD_EXPLICIT_SCHED);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_WAIT_THREAD_POLICY, SCHED_OTHER);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_WAIT_THREAD_PRIORITY, 0);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_WAIT_THREAD_INHERITSCHED, PTHREAD_INHERIT_SCHED);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_THREAD_POLICY, RTSYN_ENGINE_DEFAULT_RT_THREAD_POLICY);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_THREAD_PRIORITY, RTSYN_ENGINE_DEFAULT_RT_THREAD_PRIORITY);
    EXPECT_EQ(RTSYN_ENGINE_DEFAULT_THREAD_INHERITSCHED,
              RTSYN_ENGINE_DEFAULT_RT_THREAD_INHERITSCHED);
}
